name: Build and deploy Python app to Azure Web App - appdash

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Cloner le dépôt Git
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          cd Desktop/dash
          pip install -r requirements.txt

      # Zipper les fichiers pour le déploiement
      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appdash'  # Nom de votre application Azure
          publish-profile: ${{ secrets.AZURE }}  # Secret contenant le profil de publication  
          package: '.'  # Répertoire contenant les fichiers de l'application après le dézippage
